version: '3.9'

services:
  database:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234_aaa
      - MYSQL_DATABASE=class101
      - MYSQL_USER=swd
      - MYSQL_PASSWORD=1234

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    working_dir: /app/class101_backend
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input && uwsgi --ini uwsgi.ini"
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - static_volume:/app/static
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - database

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./:/app
      - ./log:/var/log/nginx
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - static_volume:/app/static
    depends_on:
      - database
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

volumes:
    static_volume: